#include <bits/stdc++.h>
using namespace std;
long long up1,up2,up3,down1,down2,down3,temp,ans;
signed main(){
    ios_base::sync_with_stdio(false);
    cin.tie(0); cout.tie(0);
    cin >> up1 >> up2 >> up3;
    cin >> down1 >> down2 >> down3;
    temp = min(up3,down3);
    up3 -= temp;
    down3 -= temp;
    ans += (temp*9);
        temp = min(up3,min(down1,down2));
        up3 -= temp;
        down1 -= temp;
        down2 -= temp;
        ans += (temp*9);
        temp = min(down3,min(up1,up2));
        down3 -= temp;
        up1 -= temp;       
        up2 -= temp;
    ans += (temp*9);
        temp = min(up3,down1/3);
        up3 -= temp;
        up1 -= temp;
    /*    temp = min(down3,up1/3);
        down3 -= temp;
        up1 -= temp;
    }*/
    ans += (temp*9); 
    temp = min(up1,min(up3,down2/2));
    up1 -=temp;
    up3 -= temp;
    down2 -= temp;
    ans += (temp*12);
    temp = min(down1,min(down3,up2/2));
    down1 -=temp;
    down3 -= temp;
    up2 -= temp;
    ans += (temp*12);
    temp = min(up2/3,down3/2);
    up2 -= temp;
    down3 -= temp;
    ans += (temp*24);
    temp = min(down2/3,up3/2);
    down2 -= temp;
    up3 -= temp;
    ans += (temp*24);
    temp = min(up2,down2);
    up2 -= temp;
    down2 -=temp;
    ans += (temp*4);
        temp = min(up2,down1/2);
        up2 -= temp;
        down1 -= temp;
        ans += (temp*4);
        temp = min(down2,up1/2);
        down2 -= temp;
        up1 -= temp;
    ans += (temp*4);
    temp = min(up1,down1);
    up1 -= temp;
    down1 -= temp;
    ans += temp;
    cout << ans;
} // 5 0 1 0 4 0 